spring:
  elasticsearch:
    enable: true
    uris: 159.75.225.162:9200
    host: 159.75.225.162
    port: 9200
    username: elastic
    password: xNit99mzkgKjstx_UhsH
    index: indexName
    crtName: http_ca.crt
