springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: true
    # 默认为false，改为true，相当于为每个请求参数添加了@ParameterObject
knife4j:
  # 开启增强
  enable: true
  # 开启登录认证
  basic:
    enable: true
    username: admin
    password: 123456


