spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://159.75.225.162:3306/test?serverTimezone=UTC
      username: admin
      password: sgugo2020!

mybatis:
  # mapper映射文件所在的目录
  mapper-locations: classpath:mapper/*.xml
  # 返回值类型的别名：简化实体类的写法，不用写全类名了
  type-aliases-package: com.sbtest.security.entity
  configuration:
    # 是否开启驼峰映射
    map-underscore-to-camel-case: true
    # 控制台打印mapper执行的SQL语句，用于调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 延迟加载的全局开关，默认值false为不开启，
    # 实际开发中，大部分都是需要使用延迟加载的
    lazy-loading-enabled: true
    # 开启二级缓存
    cache-enabled: true
